---
title: "Procesamiento espacial"
author: "Iñigo Sánchez Méndez"
date: "6 de enero de 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introducción

El término dominio espacial hace referencia al plano de la imagen. Los métodos de transformación de imagen en esta categoría se basan en la manipulación directa de los pixeles de la imagen.
$$g(x,y)=T[f(x,y)]$$ Donde:

- Imagen original $f(x,y)$
- Imagen transformada $g(x,y)$
- T es un operador sobre $f$ definido sobre un vecindario del punto $(x,y)$

Las dos categorias principales delprocesamiento espacial son _transformación de intensidad_ y _filtrado espacial_
En el procesamiento de la imagen usualmente se recorren los píxeles de izquierda a derecha y de arriba a abajo y se rellenan los bordes de la imagen.

## Transformaciones de intensidad y filtrado espacial

- Filtro espacial (_máscara, kernel, ventana_): definido por el vecindario de un pixel y las operaciones.
- Caso especial: vecindario $1x1$, transformación de intensidad (nivel de gris)

# Funciones básicas de transformación de intensidad

Técnicas de procesamiento de imagen más simple. Permiten transformar los valores de intensidad:
$$s=T(r)$$
En el realce de imágenes se usan tres tipos básicos de funciones:
- lineales
- logaritmicas 
- potencias

## Negativo de una imagen

Disponemos de una imagen digital con $L$ niveles de intensidad $0,1,\dots,L-1$ (Valores de intensidad $8.bits, L = 256$ se usa la transformación):

$$s = (L-1)-r$$

## Transformaciones logarítmicas

La forma general es: $$s=clog(r+1)$$

donde $c$ es una constante:

- Transforma el intervalo de intensidades bajas (oscuras) a un intervalo más amplio de intensidades (reduciendo el intervalo de las intensidades más altas).
- El inversa del logaritmo hace lo mismo con las intensidades más altas.

Comprime el rango dinámico de imágenes con gran variación en los valores de
intensidad: representación de espectros de Fourier (rango de $1$ a $10^6$ por ejemplo).
Son preferibles funciones más suaves (potencias) para realzar imágenes reales
(físicas).

## Transformaciones $gamma$ (_ley de potencia_)

- La forma más básica de la función de transformación es: $$s = cr^{\gamma}$$
Siendo $c$ y $\gamma$ constantes.
- El valor de $\gamma$ suele darse para el intervalo de intensidades escalado $[0,1]$, así la función es independiente de $L$ y $c = 1$
- Familia de transformaciones para distintos valores de $gamma$: rango más amplio para intensidades oscuras con $\gamma < 1$, rango más amplio para intensidades altas con $\gamma > 1$

Corrección de gamma también varian las relaciones entre los colores rojo, verde y azul que componen la imágen.

## Funciones analíticas a trozos

Una aproximación complementaria a los métodos anteriores, consiste en utilizar funciones analíticas a trozaos para definir los niveles de intensidad en lugar de funciones analíticas para definir la transformación de la intensidad.

La ventaja consiste en que la forma de las funciones puede ser tan compleja como se necesite. La desventaja es que requiere más trabajo por parte del usuario a la hora de definir la función.

Ejemplo: __Estiramiento del contraste__ en un intervalo de intensidades de interés $[ r1, r2 ]$ que se transforma linealmente en $[s1 , s2] (r2 - r1 < s2 - s1 )$ y reducción del contraste fuera de $[r1 , r2]$.

## Corte de nivel de intensidad

Funciones de transformación de intensidad que no son monotonas, no son del tipo:
$$T(r_{1})<T(r_{2}) para r_{1} < r_{2}$$.

Corte o _slice_ de nivel de intensidad en el que a la intensidad de entrada se le asigna una intensidad de salida en el intervalo de intensidades de interés. $$T(r)=s_{h}$$, intervalo de interés $[r_{1}, r_{2}]$ sien do $s_{h}$ un valor de intensidad alto (blanco) y constante.

Fuera del intervalo de interés o bien se mantiene una intensidad constante baja (imagen bienaria) o se mantiene la intensidad original, es decir la intensidad no se modificaría fuera del intervalo de interés:

- $T(r) = s_{i}$ constante (negro)
- $T(r) = r$

## Corte de plano de bit

Para evaluar la cuantización o compresión de una imagen. Es una transformación no monotona, descompone la imagen en sus planos de bits para analizar la importancia relativa de cada bit en la imagen. Ayuda a determinar la ideoneidaz del número de bits utilizados en la cuantización de la imagen y que también se utiliza en la compresión de imágenes.

# Procesamiento del histogramas

Conceptos estadísticos que se utilizan en el procesamiento de imágenes.

- Histograma de una imagen digital con valores de intensidad $k=0,1,\dots,L-1$: representación gráfica de la función discreta $h(r_{k}=n_{k})$, número de píxeles con valor de intensidad $r_{k}$

- Histograma normalizado: dividir $n_{k}$ por el número total de pixeles. $p(r_{k})=n_{k}/MN$, para una imágen de $MxN$. Probabilidades muestrales de los niveles de intensidad en la imagen.

- Son la base de numerosas técnicas de preprocesamiento en el dominio espacial. Por ejemplo para realzado de imágenes.

En los histogramas se reflejan las siguientes características entre otras:

- El rango dinámico de intensidad: amplio o reducido.
- Contraste (nivel de detalle): varianza de la intensidad

## Ecualización de histogramas

Se transforma la intensidad $s = T(r)$ produciendo una himagen cuyo histograma es uniforme (aproximadamente):
- Rango dinámico máximo
- Contraster alto pero preservando los grises.

La función $T$ que transforme el intervalo de intensidades $[0, L-1]$ ha de ser:
- Monótona creciente.
- Invertible, $r = T^{-1}(s)$

Suponemos un modelo probabilístico de la imagen: $p(r_{k}) = n_{k}/MN$, probabilidad del valor de intensidad $r_{k}, k = 0,1,\dots,_-1$.

El histograma de una imagen digital representa gráficamente las probabilidades de una variable aleatoria discreta.

Consideramos las intensidades de píxel al intervalo normalizado $[0,L-1]: r_{k} = k, para k = 0,1,\dots,L-1$.

La función de transformación de la intensidad para la ecualización del histograma es: $$T(r) = T(k) = (L-1)\sum_{r_{j}<r_{k}}{pj} = \frac{L-1}{MN}\sum_{j=0}^{k}{n_{j}}$$

para $r=0,1,\dots,L-1$ (y redondear a $0,1,\dots,L-1)$

Se calcula de nuevo el histograma para los valores transformados. Aparecerá ahora un histograma con una distribución más uniforme.

## Especificación de histogramas

La ecualización de un histograma busca su transformación en un histograma uniforme. Sin embargo la _especificación de un histograma_ busca realzar la imagen digital transformándolo a un histograma específico (no uniforme), dependiente de la aplicación. En general es un método de ensayo.

Planteamiento del problema:

- Histograma de una imagen digital: $p(r_{k}) = n_{k}/MN$
- Histograma especificado: $q(s_{k}),k=0,1,\dots,L-1$

- Algoritmo para obtener la función $T(r)$ que transforma (aproximadamente) el histograma inicial en el histograma especificado:
    - Calcular la función $T_{1}$ que ecualiza el histograma inicial.
    - Calcular la función $T_{2}$ que ecualiza el histograma especificado.
- Función de transformación de intensidad:
$$T(r)=T^{-1}_{2}(T_{1}(r))$$
El valor $s=T1(r)$ no se redondea; $T_{2}^{-1}(s)$ es entero.

# Fundamentos de filtrado espacial

Para realzar imágenes digitales. 

Filtro espacial (máscara, kernel, ventana): definido por un vecindario y unas
operaciones. La denominación proviene del procesamiento en el dominio de
frecuencia: equivalencia con los filtros espaciales lineales (pero no con los no
lineales).

Filtro espacial lineal con máscara $m x n$:

$$g(x,y) = \sum_{s=-a}^{a}\sum{s=-b}^{b}{w(s,t)f(x+s,y+t)}$$

siendo $m=2a+1$ y $n=2b+1$ (filtros de tamaño impar). Se procesa toda la imagen. Los coeficientes del filtro forman una matriz: $$[w(s,t)] mxn$$ 

- _Correlación_
- _Convolución_

# Filtros espaciales de suavizado

Reducción de ruido pero imagen más borrosa.

Máscaras de suavizado: _promedio_ de las intensidades en el vecindario de cada píxel y _promedio ponderado_.

## Filtros no lineales

- Estadístico de orden: se ordenan los pixeles del vecindario según su intensidad y se selecciona cierto valor de la ordenación, p. e. la _mediana_.

Reduce el ruido de la imagen sin producir una imagen tan borrosa como los filtros lineales. Se pueden usar otros estadísticos de orden (_max,min_).

# Filtros espaciales de aguzamiento

Resaltar las transiciones de intensidad

# Combinación de métodos 

# Técnicas fuzzy





