properties([pipelineTriggers([githubPush()])])
node {
    def img
    docker.withServer("${SERVER}") {
    stage ("Get source from Git"){
        git branch:"develop",url:"https://github.com/spolex/docker-pyrestfmri.git"
    }
    stage ("Generate Dockerfile") {
     sh "hostname"
     sh "./pyrestfmri/generate_docker.sh > Dockerfile"
     }
    stage ("Build image") {
            img = docker.build("spolex/pyrestfmri:${VERSION}.${env.BUILD_NUMBER}", "--network host --no-cache .")
            docker.build("spolex/pyrestfmri:latest", "--network host .")
     }
     stage('Test image') {
        /* Ideally, we would run a test framework against our image.*/
        img.inside {
            sh 'echo "Tests passed"'
        }
    }
    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            //img.push("${env.BUILD_NUMBER}")
            //img.push("latest")
        }
    }
    }
}